# Generated by Django 2.1.15 on 2021-03-16 23:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date and time this object was created.')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.')),
                ('target_object_id', models.PositiveIntegerField()),
                ('state_type', models.CharField(choices=[('State', 'State'), ('Temperature', 'Temperature'), ('Mode', 'Mode'), ('Temperature set point', 'Temperature set point')], help_text='Type of the state that has been changed', max_length=25)),
                ('from_state', models.CharField(help_text='Thermostat mode, light state or room temperature value, that has been changed', max_length=6)),
                ('to_state', models.CharField(help_text='New value for thermostat mode, light state or room temperature', max_length=6)),
                ('target_content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'homes'), ('model', 'light')), models.Q(('app_label', 'homes'), ('model', 'room')), models.Q(('app_label', 'homes'), ('model', 'thermostat')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='house',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time this object was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='house',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.'),
        ),
        migrations.AddField(
            model_name='light',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time this object was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='light',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.'),
        ),
        migrations.AddField(
            model_name='room',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time this object was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.'),
        ),
        migrations.AddField(
            model_name='thermostat',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date and time this object was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thermostat',
            name='modified',
            field=models.DateTimeField(auto_now=True, help_text='Date and time this object was last modified.'),
        ),
    ]
